<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Tag>
 */
class TagFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */

    public function definition(): array
    {
        $tags = [
            'frontend',
            'backend',
            'fullstack',
            'API',
            'UI/UX',
            'database',
            'devops',
            'machine learning',
            'AI',
            'cloud',
            'mobile',
            'web development',
            'security',
            'testing',
            'automation',
            'docker',
            'kubernetes',
            'networking',
            'data science',
            'big data',
            'blockchain',
            'IoT',
            'AR/VR',
            'game development',
            'e-commerce',
            'fintech',
            'healthtech',
            'edtech',
            'project management',
            'agile',
            'scrum',
            'serverless',
            'microservices',
            'design patterns',
            'refactoring',
            'debugging',
            'version control',
            'CI/CD',
            'containerization',
            'RESTful',
            'GraphQL',
            'NoSQL',
            'SQL',
            'PHP',
            'JavaScript',
            'TypeScript',
            'Python',
            'Java',
            'Ruby',
            'C++',
            'C#',
            'Go',
            'Swift',
            'Objective-C',
            'React',
            'Angular',
            'Vue',
            'Svelte',
            'Django',
            'Flask',
            'Laravel',
            'Symfony',
            'Spring',
            'ASP.NET',
            'Node.js',
            'Express.js',
            'Next.js',
            'Nuxt.js',
            'Flutter',
            'React Native',
            'SwiftUI',
            'Kotlin',
            'Android',
            'iOS',
            'AWS',
            'Azure',
            'Google Cloud',
            'Terraform',
            'Ansible',
            'Puppet',
            'Chef',
            'Jenkins',
            'Travis CI',
            'CircleCI',
            'ElasticSearch',
            'Redis',
            'PostgreSQL',
            'MySQL',
            'MongoDB',
            'Firebase',
            'RabbitMQ',
            'Kafka',
            'Event-Driven Architecture',
            'CQRS',
            'DDD (Domain-Driven Design)',
            'Pair Programming',
            'Code Review',
            'Continuous Integration',
            'Continuous Deployment',
            'Monitoring',
            'Logging',
            'Error Handling',
            'Authorization',
            'Authentication',
            'OAuth',
            'JWT',
            'SSL/TLS',
            'Cryptography',
            'Penetration Testing',
            'Load Balancing',
            'Caching',
            'WebSockets',
            'Service Workers',
            'PWA ',
            '(SPA)',
            '(SSR)',
            '(SSG)',
            'Headless CMS',
            '(CDN)',
            'Web Accessibility',
            'Localization (l10n)',
            'Data Visualization',
            'Data Warehousing',
            'Data Lake',
            'Data Mining',
            'Predictive Analytics',
            'Computer Vision',
            'Robotics',
            'Edge Computing',
            'Quantum Computing',
            'Digital Twins',
            '5G',
            'Smart Cities',
            'Wearables',
            'Telemedicine',
            'Remote Work Tools'
        ];
        return [
            'name' => $this->faker->randomElement($tags),
        ];
    }
}
